### ISSUE TITLE
Sidebar - Sidebar doesn't show after creating a default admin user

### ISSUE THREAD

**Issue by thaotram** [phamhongphuc/uit.hotel#362]
**Commit SHA** 62d8467b5c5ef8f952c41e6f6d17722d9986d3c9

**Description**
+ The sidebar doesn't show after creating a default admin user.

**Steps to Reproduce**
+ Empty Database.
+ Create a default admin account.
+ The app auto redirect to '/' (dashboard).
+ Left sidebar show empty **(bug)**.

**Expected Results**
  + The app shouldn't auto redirects to '/'.

**More details**
  + It's work after logout and login again.

**Comment by phamhongphuc** [comment]
close

**Comment by phamhongphuc** [comment]
The app won't auto redirects to '/'.

**Comment by thaotram** [comment]
![image](https://user-images.githubusercontent.com/33089158/58693911-04da0c80-83bc-11e9-988f-7f1540b0c4ec.png)
