### ISSUE TITLE
Popup - Close button shouldn't have box-shadow

### ISSUE THREAD

**Issue by thaotram** [phamhongphuc/uit.hotel#363]
**Commit SHA** 62d8467b5c5ef8f952c41e6f6d17722d9986d3c9

**Description** 
+ The close button shouldn't have box-shadow.

**Steps to Reproduce**
+ When the user opens any popup

**Screenshots**

![image](https://user-images.githubusercontent.com/33089158/58447998-93d2f480-8130-11e9-812c-db28613897f4.png)

**Comment by thaotram** [comment]
Các Popup bị lỗi tương tự:

- [ ] Quản lý kinh doanh > Quản lý dịch vụ > **Thêm dịch vụ**
![image](https://user-images.githubusercontent.com/33089158/58541252-471d1580-8225-11e9-9913-ae31185846a6.png)

- [ ] Quản lý kinh doanh > Quản lý giá > **Thêm giá cơ bản mới**
![image](https://user-images.githubusercontent.com/33089158/58541299-6025c680-8225-11e9-895e-2a3bb9627f55.png)

- [ ] Quản lý nhân sự > Quản lý phân quyền > **Thêm vị trí mới**
![image](https://user-images.githubusercontent.com/33089158/58541339-79c70e00-8225-11e9-8b19-93a51b7d57b1.png)

- [ ] Quản lý nhân sự > Quản lý nhân viên > **Thêm nhân viên mới**
![image](https://user-images.githubusercontent.com/33089158/58541389-9f541780-8225-11e9-816f-315bd30b95d2.png)

- [ ] Cài đặt khách sạn > Quản lý tầng phòng > **Thêm tầng mới**
![image](https://user-images.githubusercontent.com/33089158/58541482-cca0c580-8225-11e9-8288-89830c3222ae.png)

- [ ] Cài đặt khách sạn > Quản lý loại phòng > **Thêm loại phòng mới**
![image](https://user-images.githubusercontent.com/33089158/58541510-dcb8a500-8225-11e9-966f-1ca9d155ef16.png)

- [ ] Cài đặt khách sạn > Quản lý loại khách hàng > **Thêm loại khách hàng mới**
![image](https://user-images.githubusercontent.com/33089158/58541550-f528bf80-8225-11e9-8fa7-51c8ae358069.png)

**Comment by phamhongphuc** [comment]
The bug is fixed on every popup.
This issue will automatically close after the pull request #371 is merged.
