### ISSUE TITLE
Patron - Create a Patron without any Patron Kind

### ISSUE THREAD

**Issue by thaotram** [phamhongphuc/uit.hotel#364]
**Commit SHA** 62d8467b5c5ef8f952c41e6f6d17722d9986d3c9

**Description** 
- Create a new patron without any patron kind in the database will throw an error.

**To Reproduce**
1. Empty Database **(Don't have any patron kind)**.
2. Go to **receptionist/map**.
3. Click **Đặt phòng nhận ngay** > **Thêm khách hàng**.
4. Fill all form inputs with normal value > Click "Thêm".
5. See error.

**Screenshots**

![image](https://user-images.githubusercontent.com/33089158/58459672-246ffb80-8156-11e9-842b-62aae79d7f78.png)

**Comment by phamhongphuc** [comment]
In the create patron popup, we should add a dropdown to select a patron type.

**Comment by phamhongphuc** [comment]
If the application doesn't have any **Patron Kind**, we should show a message about this situation.
