### ISSUE TITLE
Room, Floor, RoomKind, PatronKind, Services, Position - Multiple items shouldn't have the same value

### ISSUE THREAD

**Issue by thaotram** [phamhongphuc/uit.hotel#366]
**Commit SHA** 62d8467b5c5ef8f952c41e6f6d17722d9986d3c9

**Description**
+ Room, Floor, RoomKind, PatronKind, Service, Position - Multiple items shouldn't have the same value

**Steps to Reproduce**
+ Go to **manage/floor-room** > Click create or update **Room/Floor**
+ Go to **manage/room-kind** > Click create or update **Room Kind**
+ Go to **manage/patron-kind** > Click create or update **Patron Kind**
+ Go to **business management** > **service management** > Click create or update **Services**
+ Goto **HRM** > **position management** > Click create or update **Position**

**Expected behavior**
+ The server should show an error when the client creates a new item with the same name.

**Screenshots**

![image](https://user-images.githubusercontent.com/33089158/58461504-0ad0b300-815a-11e9-8127-af17ea1c9bf6.png)
![image](https://user-images.githubusercontent.com/33089158/58460841-99dccb80-8158-11e9-97c2-79b6651db24e.png)
![image](https://user-images.githubusercontent.com/33089158/58462727-a9f6aa00-815c-11e9-8906-e8cf25e57406.png)
![image](https://user-images.githubusercontent.com/33089158/58542302-8d737400-8227-11e9-8cdb-9c749ec546ae.png)
![image](https://user-images.githubusercontent.com/33089158/58548304-45f2e500-8233-11e9-9624-fdad2f2f2c7d.png)

**Comment by phamhongphuc** [comment]
Khi tạo loại khách hàng mới, có tên loại khách hàng trùng với loại cũ vẫn được tạo.

Commit SHAs: 62d8467b5c5ef8f952c41e6f6d17722d9986d3c9

![image](https://user-images.githubusercontent.com/33089158/58460841-99dccb80-8158-11e9-97c2-79b6651db24e.png)

Các bước:
- Cài đặt khách sạn > Quản lý loại khách hàng > Thêm loại khách hàng mới

**Comment by phamhongphuc** [comment]
Tạo phòng mới hoặc sửa phòng cũ có tên trùng với tên phòng đã có trong hệ thống vẫn không lỗi.
Tạo tầng mới có tên trùng với tầng cũ hệ thống vẫn không lỗi.

Commit SHAs: 62d8467b5c5ef8f952c41e6f6d17722d9986d3c9

![image](https://user-images.githubusercontent.com/33089158/58462727-a9f6aa00-815c-11e9-8906-e8cf25e57406.png)


Các bước:
- Cài đặt khách sạn > Quản lý Tầng phòng > Thêm/Sửa thông tin phòng
- Cài đặt khách sạn > Quản lý Tầng phòng > Thêm/Sửa thông tin tầng
