### ISSUE TITLE
Popup - Xem thông tin chi tiết của RoomKind không hoạt động

### ISSUE THREAD

**Issue by thaotram** [phamhongphuc/uit.hotel#367]
Không thấy popup xem thông tin chi tiết của Loại phòng

Commit SHAs: 62d8467b5c5ef8f952c41e6f6d17722d9986d3c9

![image](https://user-images.githubusercontent.com/33089158/58461743-93e7ea00-815a-11e9-9212-a8f4d7cd486a.png)

Các bước:
- Cài đặt khách sạn > Quản lý loại phòng
- Nhấn vào một loại phòng có trong danh sách > Xem thông tin chi tiết

**Comment by phamhongphuc** [comment]
This feature isn't available right now.
