### ISSUE TITLE
Context Menu - Receptionist/Map - Floor

### ISSUE THREAD

**Issue by thaotram** [phamhongphuc/uit.hotel#369]
**Commit SHA** 62d8467b5c5ef8f952c41e6f6d17722d9986d3c9

**Description** 
- Floor Context menu doesn't work

**Steps to Reproduce**
1. Go to 'receptionist/map'
2. Right click on a floor
3. See error

**Expected behavior**
- A clear and concise description of what you expected to happen.

**Screenshots**

![image](https://user-images.githubusercontent.com/11532116/58485162-b5ae9480-818d-11e9-8e89-4718756a498c.png)

**Comment by phamhongphuc** [comment]
Fix: Floor in **receptionist/map** shouldn't have a context menu
