### ISSUE TITLE
Booking - Check-in, check-out date time is invalid

### ISSUE THREAD

**Issue by thaotram** [phamhongphuc/uit.hotel#370]
**Commit SHA** e69ee24cabefd818035a0851a11926652188e767

**Description**
+ See error: **Check-in, check-out date time is invalid**.

**Steps to Reproduce**
+ Make reservations for room 101. The room doesn't have any deal before.
+ Fill in the form with valid check-in and check-out date time.
+ See error: **Check-in, check-out date time is invalid**.

**Screenshots**

![image](https://user-images.githubusercontent.com/33089158/58482012-c22fee80-8187-11e9-91eb-17acff8d5355.png)

**Comment by thaotram** [comment]
The following case works:
1. **Room 101 has a transaction before**, click book that room.
2. Fill in the form with check-in and check-out date time is a day in the future.

**Comment by phamhongphuc** [comment]
The reason is when an employee makes reservations for a room.
The check-in check-out date time will be the moment employee open the popup.
After a few seconds, the value in the check-in date time will be the past.
So, we can't make reservations for a room with check-in time in the past.

**Comment by phamhongphuc** [comment]
I will create a validator for the field check-in date time.
